// TRACED: AE-AUTH-003
export const BCRYPT_SALT_ROUNDS = 12;

// TRACED: AE-AUTH-004
export const ALLOWED_REGISTRATION_ROLES = ['VIEWER'] as const;

// TRACED: AE-PERF-001
export const MAX_PAGE_SIZE = 100;

// TRACED: AE-PERF-002
export const DEFAULT_PAGE_SIZE = 20;

// TRACED: AE-MON-001
export const APP_VERSION = '1.0.0';
